using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using laba4_SPP.Files;
namespace laba4_SPP.Files
{
    [TestFixture]
    public class Class1_tests
    {
        [Test]
        public void HelloWorld_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}